"""
    Snap Conversions API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import snap_business_sdk
from snap_business_sdk.model.response_error_records import ResponseErrorRecords
from snap_business_sdk.model.validated_fields import ValidatedFields
globals()['ResponseErrorRecords'] = ResponseErrorRecords
globals()['ValidatedFields'] = ValidatedFields
from snap_business_sdk.model.test_response import TestResponse


class TestTestResponse(unittest.TestCase):
    """TestResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestResponse(self):
        """Test TestResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TestResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
