"""
    Snap Conversions API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import snap_business_sdk
from snap_business_sdk.model.response_stats_test import ResponseStatsTest
globals()['ResponseStatsTest'] = ResponseStatsTest
from snap_business_sdk.model.response_stats_data import ResponseStatsData


class TestResponseStatsData(unittest.TestCase):
    """ResponseStatsData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseStatsData(self):
        """Test ResponseStatsData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ResponseStatsData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
