"""
    Snap Conversions API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import snap_business_sdk
from snap_business_sdk.model.capi_event import CapiEvent
globals()['CapiEvent'] = CapiEvent
from snap_business_sdk.model.response_logs_log import ResponseLogsLog


class TestResponseLogsLog(unittest.TestCase):
    """ResponseLogsLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseLogsLog(self):
        """Test ResponseLogsLog"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ResponseLogsLog()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
