"""
    Snap Conversions API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from snap_business_sdk.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from snap_business_sdk.exceptions import ApiAttributeError



class CapiEvent(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'pixel_id': (str,),  # noqa: E501
            'app_id': (str,),  # noqa: E501
            'snap_app_id': (str,),  # noqa: E501
            'event_type': (str,),  # noqa: E501
            'event_conversion_type': (str,),  # noqa: E501
            'event_tag': (str,),  # noqa: E501
            'timestamp': (str,),  # noqa: E501
            'hashed_email': (str,),  # noqa: E501
            'hashed_mobile_ad_id': (str,),  # noqa: E501
            'uuid_c1': (str,),  # noqa: E501
            'hashed_idfv': (str,),  # noqa: E501
            'hashed_phone_number': (str,),  # noqa: E501
            'user_agent': (str,),  # noqa: E501
            'hashed_ip_address': (str,),  # noqa: E501
            'item_category': (str,),  # noqa: E501
            'item_ids': (str,),  # noqa: E501
            'description': (str,),  # noqa: E501
            'number_items': (str,),  # noqa: E501
            'price': (str,),  # noqa: E501
            'currency': (str,),  # noqa: E501
            'transaction_id': (str,),  # noqa: E501
            'level': (str,),  # noqa: E501
            'client_dedup_id': (str,),  # noqa: E501
            'data_use': (str,),  # noqa: E501
            'search_string': (str,),  # noqa: E501
            'page_url': (str,),  # noqa: E501
            'sign_up_method': (str,),  # noqa: E501
            'hashed_first_name_sha': (str,),  # noqa: E501
            'hashed_first_name_sdx': (str,),  # noqa: E501
            'hashed_middle_name_sha': (str,),  # noqa: E501
            'hashed_middle_name_sdx': (str,),  # noqa: E501
            'hashed_last_name_sha': (str,),  # noqa: E501
            'hashed_last_name_sdx': (str,),  # noqa: E501
            'hashed_city_sha': (str,),  # noqa: E501
            'hashed_city_sdx': (str,),  # noqa: E501
            'hashed_state_sha': (str,),  # noqa: E501
            'hashed_state_sdx': (str,),  # noqa: E501
            'hashed_zip': (str,),  # noqa: E501
            'hashed_dob_month': (str,),  # noqa: E501
            'hashed_dob_day': (str,),  # noqa: E501
            'integration': (str,),  # noqa: E501
            'click_id': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'pixel_id': 'pixel_id',  # noqa: E501
        'app_id': 'app_id',  # noqa: E501
        'snap_app_id': 'snap_app_id',  # noqa: E501
        'event_type': 'event_type',  # noqa: E501
        'event_conversion_type': 'event_conversion_type',  # noqa: E501
        'event_tag': 'event_tag',  # noqa: E501
        'timestamp': 'timestamp',  # noqa: E501
        'hashed_email': 'hashed_email',  # noqa: E501
        'hashed_mobile_ad_id': 'hashed_mobile_ad_id',  # noqa: E501
        'uuid_c1': 'uuid_c1',  # noqa: E501
        'hashed_idfv': 'hashed_idfv',  # noqa: E501
        'hashed_phone_number': 'hashed_phone_number',  # noqa: E501
        'user_agent': 'user_agent',  # noqa: E501
        'hashed_ip_address': 'hashed_ip_address',  # noqa: E501
        'item_category': 'item_category',  # noqa: E501
        'item_ids': 'item_ids',  # noqa: E501
        'description': 'description',  # noqa: E501
        'number_items': 'number_items',  # noqa: E501
        'price': 'price',  # noqa: E501
        'currency': 'currency',  # noqa: E501
        'transaction_id': 'transaction_id',  # noqa: E501
        'level': 'level',  # noqa: E501
        'client_dedup_id': 'client_dedup_id',  # noqa: E501
        'data_use': 'data_use',  # noqa: E501
        'search_string': 'search_string',  # noqa: E501
        'page_url': 'page_url',  # noqa: E501
        'sign_up_method': 'sign_up_method',  # noqa: E501
        'hashed_first_name_sha': 'hashed_first_name_sha',  # noqa: E501
        'hashed_first_name_sdx': 'hashed_first_name_sdx',  # noqa: E501
        'hashed_middle_name_sha': 'hashed_middle_name_sha',  # noqa: E501
        'hashed_middle_name_sdx': 'hashed_middle_name_sdx',  # noqa: E501
        'hashed_last_name_sha': 'hashed_last_name_sha',  # noqa: E501
        'hashed_last_name_sdx': 'hashed_last_name_sdx',  # noqa: E501
        'hashed_city_sha': 'hashed_city_sha',  # noqa: E501
        'hashed_city_sdx': 'hashed_city_sdx',  # noqa: E501
        'hashed_state_sha': 'hashed_state_sha',  # noqa: E501
        'hashed_state_sdx': 'hashed_state_sdx',  # noqa: E501
        'hashed_zip': 'hashed_zip',  # noqa: E501
        'hashed_dob_month': 'hashed_dob_month',  # noqa: E501
        'hashed_dob_day': 'hashed_dob_day',  # noqa: E501
        'integration': 'integration',  # noqa: E501
        'click_id': 'click_id',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """CapiEvent - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            pixel_id (str): [optional]  # noqa: E501
            app_id (str): [optional]  # noqa: E501
            snap_app_id (str): [optional]  # noqa: E501
            event_type (str): [optional]  # noqa: E501
            event_conversion_type (str): [optional]  # noqa: E501
            event_tag (str): [optional]  # noqa: E501
            timestamp (str): [optional]  # noqa: E501
            hashed_email (str): [optional]  # noqa: E501
            hashed_mobile_ad_id (str): [optional]  # noqa: E501
            uuid_c1 (str): [optional]  # noqa: E501
            hashed_idfv (str): [optional]  # noqa: E501
            hashed_phone_number (str): [optional]  # noqa: E501
            user_agent (str): [optional]  # noqa: E501
            hashed_ip_address (str): [optional]  # noqa: E501
            item_category (str): [optional]  # noqa: E501
            item_ids (str): [optional]  # noqa: E501
            description (str): [optional]  # noqa: E501
            number_items (str): [optional]  # noqa: E501
            price (str): [optional]  # noqa: E501
            currency (str): [optional]  # noqa: E501
            transaction_id (str): [optional]  # noqa: E501
            level (str): [optional]  # noqa: E501
            client_dedup_id (str): [optional]  # noqa: E501
            data_use (str): [optional]  # noqa: E501
            search_string (str): [optional]  # noqa: E501
            page_url (str): [optional]  # noqa: E501
            sign_up_method (str): [optional]  # noqa: E501
            hashed_first_name_sha (str): [optional]  # noqa: E501
            hashed_first_name_sdx (str): [optional]  # noqa: E501
            hashed_middle_name_sha (str): [optional]  # noqa: E501
            hashed_middle_name_sdx (str): [optional]  # noqa: E501
            hashed_last_name_sha (str): [optional]  # noqa: E501
            hashed_last_name_sdx (str): [optional]  # noqa: E501
            hashed_city_sha (str): [optional]  # noqa: E501
            hashed_city_sdx (str): [optional]  # noqa: E501
            hashed_state_sha (str): [optional]  # noqa: E501
            hashed_state_sdx (str): [optional]  # noqa: E501
            hashed_zip (str): [optional]  # noqa: E501
            hashed_dob_month (str): [optional]  # noqa: E501
            hashed_dob_day (str): [optional]  # noqa: E501
            integration (str): [optional]  # noqa: E501
            click_id (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', True)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """CapiEvent - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            pixel_id (str): [optional]  # noqa: E501
            app_id (str): [optional]  # noqa: E501
            snap_app_id (str): [optional]  # noqa: E501
            event_type (str): [optional]  # noqa: E501
            event_conversion_type (str): [optional]  # noqa: E501
            event_tag (str): [optional]  # noqa: E501
            timestamp (str): [optional]  # noqa: E501
            hashed_email (str): [optional]  # noqa: E501
            hashed_mobile_ad_id (str): [optional]  # noqa: E501
            uuid_c1 (str): [optional]  # noqa: E501
            hashed_idfv (str): [optional]  # noqa: E501
            hashed_phone_number (str): [optional]  # noqa: E501
            user_agent (str): [optional]  # noqa: E501
            hashed_ip_address (str): [optional]  # noqa: E501
            item_category (str): [optional]  # noqa: E501
            item_ids (str): [optional]  # noqa: E501
            description (str): [optional]  # noqa: E501
            number_items (str): [optional]  # noqa: E501
            price (str): [optional]  # noqa: E501
            currency (str): [optional]  # noqa: E501
            transaction_id (str): [optional]  # noqa: E501
            level (str): [optional]  # noqa: E501
            client_dedup_id (str): [optional]  # noqa: E501
            data_use (str): [optional]  # noqa: E501
            search_string (str): [optional]  # noqa: E501
            page_url (str): [optional]  # noqa: E501
            sign_up_method (str): [optional]  # noqa: E501
            hashed_first_name_sha (str): [optional]  # noqa: E501
            hashed_first_name_sdx (str): [optional]  # noqa: E501
            hashed_middle_name_sha (str): [optional]  # noqa: E501
            hashed_middle_name_sdx (str): [optional]  # noqa: E501
            hashed_last_name_sha (str): [optional]  # noqa: E501
            hashed_last_name_sdx (str): [optional]  # noqa: E501
            hashed_city_sha (str): [optional]  # noqa: E501
            hashed_city_sdx (str): [optional]  # noqa: E501
            hashed_state_sha (str): [optional]  # noqa: E501
            hashed_state_sdx (str): [optional]  # noqa: E501
            hashed_zip (str): [optional]  # noqa: E501
            hashed_dob_month (str): [optional]  # noqa: E501
            hashed_dob_day (str): [optional]  # noqa: E501
            integration (str): [optional]  # noqa: E501
            click_id (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
