"""
    Snap Conversions API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import snap_business_sdk
from snap_business_sdk.model.capi_event import CapiEvent


class TestCapiEvent(unittest.TestCase):
    """CapiEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCapiEvent(self):
        """Test CapiEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CapiEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
